version: "3.8"

services:
  # PostgreSQL для разработки
  postgres:
    image: postgres:15-alpine
    container_name: agb_dev_postgres
    environment:
      POSTGRES_DB: test_platform_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_platform_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:

networks:
  dev-network:
    driver: bridge
