version: '3.8'

services:
  agb-db:
    image: postgres:15
    container_name: agb_postgres_local
    environment:
      POSTGRES_DB: agb_prod
      POSTGRES_USER: agb_user
      POSTGRES_PASSWORD: secure_password_2024
    ports:
      - "15432:5432"
    volumes:
      - agb_postgres_data:/var/lib/postgresql/data
    networks:
      - agb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agb_user -d agb_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  agb-redis:
    image: redis:7-alpine
    container_name: agb_redis_local
    ports:
      - "16379:6379"
    volumes:
      - agb_redis_data:/data
    networks:
      - agb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  agb_postgres_data:
  agb_redis_data:

networks:
  agb-network:
    driver: bridge