"""Initial migration

Revision ID: f461a92ad980
Revises: 
Create Date: 2025-09-29 15:42:14.203550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f461a92ad980'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key_settings_v3', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_api_key_settings_v3_id'), 'api_key_settings_v3', ['id'], unique=False)
    op.create_index(op.f('ix_api_key_settings_v3_service_name'), 'api_key_settings_v3', ['service_name'], unique=False)
    op.drop_constraint('api_key_settings_v3_created_by_fkey', 'api_key_settings_v3', type_='foreignkey')
    op.create_index(op.f('ix_email_settings_v3_id'), 'email_settings_v3', ['id'], unique=False)
    op.alter_column('role_permissions_v3', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_role_permissions_v3_id'), 'role_permissions_v3', ['id'], unique=False)
    op.drop_constraint('role_permissions_v3_role_id_fkey', 'role_permissions_v3', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions_v3', 'roles_v3', ['role_id'], ['id'])
    op.drop_constraint('roles_v3_name_key', 'roles_v3', type_='unique')
    op.create_index(op.f('ix_roles_v3_id'), 'roles_v3', ['id'], unique=False)
    op.create_index(op.f('ix_roles_v3_name'), 'roles_v3', ['name'], unique=True)
    op.alter_column('system_notifications_v3', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_system_notifications_v3_id'), 'system_notifications_v3', ['id'], unique=False)
    op.drop_constraint('system_notifications_v3_created_by_fkey', 'system_notifications_v3', type_='foreignkey')
    op.alter_column('system_settings_v3', 'data_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'string'::character varying"))
    op.drop_constraint('system_settings_v3_category_key_key', 'system_settings_v3', type_='unique')
    op.create_index(op.f('ix_system_settings_v3_category'), 'system_settings_v3', ['category'], unique=False)
    op.create_index(op.f('ix_system_settings_v3_id'), 'system_settings_v3', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_v3_key'), 'system_settings_v3', ['key'], unique=False)
    op.alter_column('user_activity_v3', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_activity_v3', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_activity_v3', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_activity_v3_id'), 'user_activity_v3', ['id'], unique=False)
    op.alter_column('user_roles_v3', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_roles_v3', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_user_roles_v3_id'), 'user_roles_v3', ['id'], unique=False)
    op.drop_constraint('user_roles_v3_assigned_by_fkey', 'user_roles_v3', type_='foreignkey')
    op.drop_constraint('user_roles_v3_role_id_fkey', 'user_roles_v3', type_='foreignkey')
    op.drop_constraint('user_roles_v3_user_id_fkey', 'user_roles_v3', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles_v3', 'roles_v3', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles_v3', type_='foreignkey')
    op.create_foreign_key('user_roles_v3_user_id_fkey', 'user_roles_v3', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_roles_v3_role_id_fkey', 'user_roles_v3', 'roles_v3', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_roles_v3_assigned_by_fkey', 'user_roles_v3', 'users', ['assigned_by'], ['id'])
    op.drop_index(op.f('ix_user_roles_v3_id'), table_name='user_roles_v3')
    op.alter_column('user_roles_v3', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_roles_v3', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_user_activity_v3_id'), table_name='user_activity_v3')
    op.alter_column('user_activity_v3', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_activity_v3', 'ip_address',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('user_activity_v3', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_system_settings_v3_key'), table_name='system_settings_v3')
    op.drop_index(op.f('ix_system_settings_v3_id'), table_name='system_settings_v3')
    op.drop_index(op.f('ix_system_settings_v3_category'), table_name='system_settings_v3')
    op.create_unique_constraint('system_settings_v3_category_key_key', 'system_settings_v3', ['category', 'key'])
    op.alter_column('system_settings_v3', 'data_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'string'::character varying"))
    op.create_foreign_key('system_notifications_v3_created_by_fkey', 'system_notifications_v3', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_system_notifications_v3_id'), table_name='system_notifications_v3')
    op.alter_column('system_notifications_v3', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_roles_v3_name'), table_name='roles_v3')
    op.drop_index(op.f('ix_roles_v3_id'), table_name='roles_v3')
    op.create_unique_constraint('roles_v3_name_key', 'roles_v3', ['name'])
    op.drop_constraint(None, 'role_permissions_v3', type_='foreignkey')
    op.create_foreign_key('role_permissions_v3_role_id_fkey', 'role_permissions_v3', 'roles_v3', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_role_permissions_v3_id'), table_name='role_permissions_v3')
    op.alter_column('role_permissions_v3', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_email_settings_v3_id'), table_name='email_settings_v3')
    op.create_foreign_key('api_key_settings_v3_created_by_fkey', 'api_key_settings_v3', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_api_key_settings_v3_service_name'), table_name='api_key_settings_v3')
    op.drop_index(op.f('ix_api_key_settings_v3_id'), table_name='api_key_settings_v3')
    op.alter_column('api_key_settings_v3', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
